<?php

/**
 * Implementation of hook_form_FORM_ID_alter().
 */
function autocomplete_form_alter(&$form, &$form_state, $form_id) {
  $form['title']['#autocomplete_path'] = 'unique_node_autocomplete_callback';
}

/**
 * Implements hook_menu().
 */
function autocomplete_menu() {
  $items['unique_node_autocomplete_callback'] = array(
    'page callback' => 'autocomplete_unique_node_autocomplete_callback',
    'file' => 'autocomplete.inc',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
  );

  return $items;
}
